# Generated by Django 3.0.7 on 2020-06-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_warden_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='living_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='message_to_parent',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applications',
            name='returning_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
