# Generated by Django 3.0.7 on 2020-06-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200616_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='applications',
            name='till_date',
            field=models.DateField(),
        ),
    ]
